# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-26 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
