# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='lname',
            new_name='last_name',
        ),
    ]
