# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 19:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_auto_20161026_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='email',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='last_name',
        ),
    ]
